In [1]:
import pandas as pd
df = pd.read_csv("C:\\Users\\HP\\Downloads\\customer_analytics - customer_analytics.csv")
print(df)
df.head(10)

      Customer_ID Age Annual_Income Account_Balance Credit_Score  \
0          101317  55         44033       111350.85          772
1          101001  32        215546       254378.37          374
2          101069  23        226403       159975.42          668
3          101968  66         87824        295741.6          315
4          100530  67         31570       242423.78          370
...           ...  ..           ...             ...          ...
2035       101131  42         88530       153490.72          677
2036       101295  31        205738        270989.4          392
2037       100861  25        211994       160507.65          737
2038       101460  64         30105        32117.15          794
2039       101127  55        248332       274980.99          783

      Tenure_Years       City    Segment Channel         Join_Date Active  \
0                3  Bangalore        SME   Agent  15-08-2022 00:00    Yes
1                8      Delhi     Retail   Agent  11-01-2025 00:00    Yes
2               12    Chennai    Premium   Agent  01-08-2024 00:00     No
3               14     Mumbai    Premium   Agent  15-05-2021 00:00    Yes
4                4  bangalore     Retail   Agent  03-02-2026 00:00     No
...            ...        ...        ...     ...               ...    ...
2035            12  Hyderabad     Retail   Agent  10-07-2021 00:00     No
2036             8     Mumbai  Corporate   Agent  05-07-2025 00:00    Yes
2037             8    Kolkata     Retail  Online  17-10-2022 00:00    Yes
2038             8  Bangalore     Retail   Agent  26-08-2023 00:00     No
2039             6    Chennai     Retail  Branch               NaN    Yes

     Risk_Level Monthly_Spend Transactions  Satisfaction_Score
0           Low      23066.19          135                 3.1
1          High           NaN          106                 8.2
2        Medium      28536.34          146                 6.3
3          High      12869.71          115                 9.7
4          High      34163.02           94                 3.7
...         ...           ...          ...                 ...
2035     Medium       8455.42          119                 8.6
2036       High      34087.69          134                 2.6
2037        Low      26518.74           87                 1.3
2038        Low      20943.11          107                 9.3
2039        Low      48511.32          119                 3.1

[2040 rows x 15 columns]

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,15-08-2022 00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,11-01-2025 00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,01-08-2024 00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,15-05-2021 00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,03-02-2026 00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,04-06-2023 00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,16-01-2024 00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,26-06-2024 00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,12-03-2025 00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,07-10-2021 00:00,Yes,Medium,11472.36,124,9.1

In [2]:
df.head()

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,15-08-2022 00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,11-01-2025 00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,01-08-2024 00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,15-05-2021 00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,03-02-2026 00:00,No,High,34163.02,94,3.7

In [3]:
df.tail(100)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
1940,101580,54,121111,272174.68,558,2,Delhi,SME,Online,21-05-2021 00:00,Yes,Medium,20233.63,37,4.7
1941,100730,29,190140,21633.33,654,4,Chennai,SME,Online,15-09-2022 00:00,Yes,Medium,9595.08,71,8.7
1942,100402,50,56585,119294.27,678,3,Delhi,Retail,Branch,05-02-2025 00:00,No,Medium,14612.43,55,4.7
1943,100703,34,204785,203145.72,372,10,Pune,Corporate,Online,18-01-2026 00:00,Yes,High,14970.31,93,7.7
1944,101501,67,30347,185083.21,693,8,Pune,Corporate,Agent,05-02-2024 00:00,No,Medium,14206.63,43,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,10-07-2021 00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,05-07-2025 00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,17-10-2022 00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,26-08-2023 00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

In [6]:
df.describe()

         Customer_ID  Tenure_Years  Satisfaction_Score
count    2040.000000   2040.000000         1955.000000
mean   100999.696078      7.566176            5.595908
std       577.289267      4.614468            2.578004
min    100001.000000      0.000000            1.000000
25%    100500.750000      4.000000            3.400000
50%    100999.500000      8.000000            5.700000
75%    101498.250000     12.000000            7.800000
max    102000.000000     15.000000           10.000000