#### 1. Data Quality Audit
#### Perform a complete audit of the dataset:
#### • shape
#### • datatypes
#### • missing values
#### • duplicate records
#### • unique vehicle IDs
#### • categorical distributions
#### Identify every data-quality problem before modifying the dataset.

In [13]:
import pandas as pd
df = pd.read_csv("C:\\Users\\HP\\Downloads\\EV_Resale_Price_Regression - EV_Resale_Price_Regression.csv")
df

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price
0,EV-20170,2025-01-01,2021,Nexora,SUV,46.9,89.6,313.0,28454.0000,10.0,No,1,Chennai,Complete,1527836
1,EV-20530,2025-01-02,2025,Nexora,Crossover,80.6,99.5,543.0,183935.8448,7.1,No,2,Chennai,Complete,2040760
2,EV-20654,2025-01-03,2019,Nexora,Crossover,53.9,91.2,NaN,12003.0000,3.6,Yes,1,Chennai,Complete,1830249
3,EV-20935,2025-01-04,2022,GreenDrive,Hatchback,60.1,89.3,528.0,13623.0000,7.8,Yes,2,Delhi,Complete,1726422
4,EV-20827,2025-01-05,2024,GreenDrive,Sedan,53.0,92.0,264.0,28548.0000,6.1,No,1,Pune,Complete,1642232
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,EV-20357,2027-09-23,2017,E-Motion,Sedan,37.9,89.9,333.0,61861.0000,3.0,No,1,Bengaluru,Complete,1338124
996,EV-20756,2027-09-24,2020,Atheron,Hatchback,67.5,99.9,290.0,55605.0000,9.2,Yes,1,Bengaluru,Complete,1624596
997,EV-20984,2027-09-25,2025,Atheron,Crossover,91.1,81.8,434.0,23708.0000,2.0,No,1,Delhi,Partial,1958519
998,EV-20410,2027-09-26,2019,GreenDrive,Sedan,76.8,98.6,264.0,39435.0000,2.8,Yes,1,Chennai,Complete,1724555
999,EV-20168,2027-09-27,2019,Voltix,Crossover,63.6,88.2,150.0,103173.0000,NaN,No,3,Pune,Complete,1232571

In [10]:
df.shape

(1000, 15)

In [15]:
df.isnull()

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [23]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [26]:
df=df['vehicle_id'].unique()
df

array(['EV-20170', 'EV-20530', 'EV-20654', 'EV-20935', 'EV-20827',
       'EV-20547', 'EV-20961', 'EV-20584', 'EV-20708', 'EV-20059',
       'EV-20859', 'EV-20922', 'EV-20381', 'EV-20023', 'EV-20541',
       'EV-20445', 'EV-20256', 'EV-20236', 'EV-20956', 'EV-20301',
       'EV-20929', 'EV-20934', 'EV-20842', 'EV-20663', 'EV-20501',
       'EV-20421', 'EV-20208', 'EV-20085', 'EV-20997', 'EV-20349',
       'EV-20861', 'EV-20891', 'EV-20004', 'EV-20437', 'EV-20044',
       'EV-20163', 'EV-20497', 'EV-20969', 'EV-20848', 'EV-20903',
       'EV-20674', 'EV-20056', 'EV-20343', 'EV-20581', 'EV-20493',
       'EV-20644', 'EV-20867', 'EV-20267', 'EV-20252', 'EV-20767',
       'EV-20986', 'EV-20007', 'EV-20560', 'EV-20074', 'EV-20838',
       'EV-20028', 'EV-20237', 'EV-20473', 'EV-20506', 'EV-20959',
       'EV-20980', 'EV-20577', 'EV-20552', 'EV-20782', 'EV-20753',
       'EV-20356', 'EV-20360', 'EV-20380', 'EV-20412', 'EV-20257',
       'EV-20251', 'EV-20973', 'EV-20515', 'EV-20713', 'EV-20392',
       'EV-20874', 'EV-20078', 'EV-20049', 'EV-20715', 'EV-20382',
       'EV-20549', 'EV-20653', 'EV-20386', 'EV-20455', 'EV-20238',
       'EV-20175', 'EV-20285', 'EV-20622', 'EV-20955', 'EV-20452',
       'EV-20630', 'EV-20607', 'EV-20399', 'EV-20309', 'EV-20563',
       'EV-20316', 'EV-20142', 'EV-20384', 'EV-20254', 'EV-20488',
       'EV-20606', 'EV-20276', 'EV-20667', 'EV-20833', 'EV-20777',
       'EV-20274', 'EV-20026', 'EV-20448', 'EV-20938', 'EV-20122',
       'EV-20507', 'EV-20873', 'EV-20203', 'EV-20524', 'EV-20234',
       'EV-20626', 'EV-20325', 'EV-20693', 'EV-20119', 'EV-20011',
       'EV-20832', 'EV-20977', 'EV-20318', 'EV-20288', 'EV-20598',
       'EV-20926', 'EV-20870', 'EV-20354', 'EV-20403', 'EV-20246',
       'EV-20185', 'EV-20856', 'EV-20932', 'EV-20544', 'EV-20646',
       'EV-20865', 'EV-20845', 'EV-20499', 'EV-20013', 'EV-20278',
       'EV-20359', 'EV-20215', 'EV-20783', 'EV-20949', 'EV-20114',
       'EV-20282', 'EV-20365', 'EV-20420', 'EV-20292', 'EV-20127',
       'EV-20757', 'EV-20518', 'EV-20916', 'EV-20565', 'EV-20402',
       'EV-20502', 'EV-20051', 'EV-20751', 'EV-20140', 'EV-20247',
       'EV-20662', 'EV-20456', 'EV-20138', 'EV-20696', 'EV-20090',
       'EV-20416', 'EV-20786', 'EV-20917', 'EV-20103', 'EV-20083',
       'EV-20352', 'EV-20655', 'EV-20183', 'EV-20459', 'EV-20726',
       'EV-20627', 'EV-20221', 'EV-20323', 'EV-20614', 'EV-20066',
       'EV-20091', 'EV-20190', 'EV-20465', 'EV-20789', 'EV-20562',
       'EV-20355', 'EV-20393', 'EV-20405', 'EV-20423', 'EV-20719',
       'EV-20275', 'EV-20120', 'EV-20330', 'EV-20561', 'EV-20480',
       'EV-20554', 'EV-20920', 'EV-20553', 'EV-20945', 'EV-20165',
       'EV-20250', 'EV-20860', 'EV-20571', 'EV-20730', 'EV-20564',
       'EV-20855', 'EV-20609', 'EV-20006', 'EV-20557', 'EV-20613',
       'EV-20580', 'EV-20308', 'EV-20936', 'EV-20505', 'EV-20336',
       'EV-20100', 'EV-20024', 'EV-20152', 'EV-20625', 'EV-20483',
       'EV-20729', 'EV-20391', 'EV-20220', 'EV-20040', 'EV-20850',
       'EV-20734', 'EV-20831', 'EV-20198', 'EV-20720', 'EV-20749',
       'EV-20202', 'EV-20419', 'EV-20228', 'EV-20639', 'EV-20780',
       'EV-20379', 'EV-20342', 'EV-20910', 'EV-20939', 'EV-20877',
       'EV-20123', 'EV-20081', 'EV-20807', 'EV-20339', 'EV-20242',
       'EV-20645', 'EV-20843', 'EV-20347', 'EV-20643', 'EV-20679',
       'EV-20270', 'EV-20778', 'EV-20370', 'EV-20464', 'EV-20048',
       'EV-20583', 'EV-20803', 'EV-20908', 'EV-20121', 'EV-20924',
       'EV-20468', 'EV-20160', 'EV-20815', 'EV-20535', 'EV-20657',
       'EV-20439', 'EV-20612', 'EV-20551', 'EV-20229', 'EV-20597',
       'EV-20337', 'EV-20539', 'EV-20147', 'EV-20030', 'EV-20333',
       'EV-20954', 'EV-20451', 'EV-20187', 'EV-20272', 'EV-20897',
       'EV-20450', 'EV-20050', 'EV-20025', 'EV-20695', 'EV-20885',
       'EV-20136', 'EV-20162', 'EV-20566', 'EV-20517', 'EV-20314',
       'EV-20440', 'EV-20839', 'EV-20640', 'EV-20364', 'EV-20545',
       'EV-20255', 'EV-20745', 'EV-20171', 'EV-20587', 'EV-20297',
       'EV-20741', 'EV-20390', 'EV-20476', 'EV-20230', 'EV-20377',
       'EV-20133', 'EV-20681', 'EV-20478', 'EV-20835', 'EV-20358',
       'EV-20813', 'EV-20511', 'EV-20003', 'EV-20268', 'EV-20635',
       'EV-20523', 'EV-20179', 'EV-20491', 'EV-20656', 'EV-20892',
       'EV-20425', 'EV-20893', 'EV-20166', 'EV-20259', 'EV-20043',
       'EV-20883', 'EV-20871', 'EV-20520', 'EV-20596', 'EV-20134',
       'EV-20528', 'EV-20559', 'EV-20243', 'EV-20727', 'EV-20260',
       'EV-20810', 'EV-20398', 'EV-20155', 'EV-20153', 'EV-20868',
       'EV-20353', 'EV-20886', 'EV-20853', 'EV-20315', 'EV-20186',
       'EV-20469', 'EV-20180', 'EV-20079', 'EV-20490', 'EV-20537',
       'EV-20249', 'EV-20407', 'EV-20145', 'EV-20383', 'EV-20985',
       'EV-20104', 'EV-20652', 'EV-20904', 'EV-20489', 'EV-20068',
       'EV-20054', 'EV-20854', 'EV-20306', 'EV-20691', 'EV-20516',
       'EV-20351', 'EV-20796', 'EV-20291', 'EV-20841', 'EV-20923',
       'EV-20408', 'EV-20001', 'EV-20486', 'EV-20484', 'EV-20115',
       'EV-20295', 'EV-20241', 'EV-20245', 'EV-20154', 'EV-20532',
       'EV-20834', 'EV-20890', 'EV-20993', 'EV-20814', 'EV-20825',
       'EV-20058', 'EV-20071', 'EV-20572', 'EV-20300', 'EV-20404',
       'EV-20928', 'EV-20110', 'EV-20471', 'EV-20600', 'EV-20690',
       'EV-20201', 'EV-20307', 'EV-20701', 'EV-20304', 'EV-20101',
       'EV-20015', 'EV-20424', 'EV-20061', 'EV-20651', 'EV-20210',
       'EV-20965', 'EV-20953', 'EV-20311', 'EV-20338', 'EV-20601',
       'EV-20107', 'EV-20620', 'EV-20146', 'EV-20041', 'EV-20692',
       'EV-20206', 'EV-20492', 'EV-20321', 'EV-20642', 'EV-20901',
       'EV-20957', 'EV-20919', 'EV-20366', 'EV-20895', 'EV-20664',
       'EV-20800', 'EV-20752', 'EV-20264', 'EV-20105', 'EV-20869',
       'EV-20065', 'EV-20792', 'EV-20941', 'EV-20704', 'EV-20269',
       'EV-20900', 'EV-20611', 'EV-20389', 'EV-20233', 'EV-20199',
       'EV-20707', 'EV-20593', 'EV-20097', 'EV-20019', 'EV-20682',
       'EV-20648', 'EV-20931', 'EV-20589', 'EV-20921', 'EV-20029',
       'EV-20240', 'EV-20217', 'EV-20158', 'EV-20156', 'EV-20705',
       'EV-20819', 'EV-20109', 'EV-20703', 'EV-20453', 'EV-20371',
       'EV-20616', 'EV-20536', 'EV-20872', 'EV-20436', 'EV-20432',
       'EV-20151', 'EV-20540', 'EV-20099', 'EV-20660', 'EV-20556',
       'EV-20947', 'EV-20617', 'EV-20852', 'EV-20676', 'EV-20289',
       'EV-20687', 'EV-20942', 'EV-20108', 'EV-20296', 'EV-20021',
       'EV-20846', 'EV-20460', 'EV-20888', 'EV-20636', 'EV-20332',
       'EV-20709', 'EV-20770', 'EV-20585', 'EV-20918', 'EV-20629',
       'EV-20631', 'EV-20273', 'EV-20435', 'EV-20599', 'EV-20057',
       'EV-20650', 'EV-20430', 'EV-20685', 'EV-20253', 'EV-20739',
       'EV-20940', 'EV-20797', 'EV-20182', 'EV-20721', 'EV-20735',
       'EV-20579', 'EV-20413', 'EV-20913', 'EV-20974', 'EV-20239',
       'EV-20470', 'EV-20866', 'EV-20495', 'EV-20952', 'EV-20963',
       'EV-20542', 'EV-20927', 'EV-20878', 'EV-20879', 'EV-20176',
       'EV-20864', 'EV-20668', 'EV-20461', 'EV-20326', 'EV-20373',
       'EV-20070', 'EV-20983', 'EV-20426', 'EV-20340', 'EV-20418',
       'EV-20042', 'EV-20284', 'EV-20335', 'EV-20063', 'EV-20964',
       'EV-20784', 'EV-20433', 'EV-20227', 'EV-20534', 'EV-20671',
       'EV-20008', 'EV-20293', 'EV-20623', 'EV-20271', 'EV-20746',
       'EV-20930', 'EV-20060', 'EV-20035', 'EV-20248', 'EV-20294',
       'EV-20069', 'EV-20943', 'EV-20851', 'EV-20303', 'EV-20084',
       'EV-20798', 'EV-20688', 'EV-20226', 'EV-20177', 'EV-20738',
       'EV-20527', 'EV-20283', 'EV-20824', 'EV-20960', 'EV-20262',
       'EV-20225', 'EV-20658', 'EV-20950', 'EV-20967', 'EV-20388',
       'EV-20776', 'EV-20494', 'EV-20790', 'EV-20806', 'EV-20067',
       'EV-20287', 'EV-20966', 'EV-20331', 'EV-20857', 'EV-20533',
       'EV-20526', 'EV-20998', 'EV-20822', 'EV-20817', 'EV-20905',
       'EV-20216', 'EV-20244', 'EV-20618', 'EV-20387', 'EV-20801',
       'EV-20894', 'EV-20647', 'EV-20764', 'EV-20409', 'EV-20902',
       'EV-20570', 'EV-20173', 'EV-20302', 'EV-20519', 'EV-20372',
       'EV-20876', 'EV-20576', 'EV-20706', 'EV-20118', 'EV-20529',
       'EV-20987', 'EV-20594', 'EV-20805', 'EV-20431', 'EV-20775',
       'EV-20214', 'EV-20619', 'EV-20169', 'EV-20191', 'EV-20829',
       'EV-20362', 'EV-20862', 'EV-20479', 'EV-20995', 'EV-20205',
       'EV-20172', 'EV-20200', 'EV-20804', 'EV-20875', 'EV-20548',
       'EV-20821', 'EV-20991', 'EV-20794', 'EV-20196', 'EV-20700',
       'EV-20569', 'EV-20979', 'EV-20602', 'EV-20633', 'EV-20889',
       'EV-20748', 'EV-20263', 'EV-20376', 'EV-20590', 'EV-20909',
       'EV-20787', 'EV-20808', 'EV-20686', 'EV-20077', 'EV-20258',
       'EV-20161', 'EV-20884', 'EV-20082', 'EV-20128', 'EV-20774',
       'EV-20802', 'EV-20317', 'EV-20578', 'EV-20193', 'EV-20117',
       'EV-20982', 'EV-20591', 'EV-20632', 'EV-20675', 'EV-20102',
       'EV-20188', 'EV-20689', 'EV-20045', 'EV-20781', 'EV-20002',
       'EV-20972', 'EV-20159', 'EV-20463', 'EV-20039', 'EV-20427',
       'EV-20933', 'EV-20710', 'EV-20098', 'EV-20911', 'EV-20699',
       'EV-20733', 'EV-20280', 'EV-20582', 'EV-20211', 'EV-20994',
       'EV-20694', 'EV-20758', 'EV-20510', 'EV-20053', 'EV-20369',
       'EV-20441', 'EV-20742', 'EV-20038', 'EV-20588', 'EV-20150',
       'EV-20141', 'EV-20032', 'EV-20728', 'EV-20073', 'EV-20677',
       'EV-20184', 'EV-20672', 'EV-20684', 'EV-20462', 'EV-20385',
       'EV-20946', 'EV-20673', 'EV-20605', 'EV-20968', 'EV-20610',
       'EV-20500', 'EV-20324', 'EV-20755', 'EV-20725', 'EV-20990',
       'EV-20126', 'EV-20970', 'EV-20785', 'EV-20396', 'EV-20374',
       'EV-20194', 'EV-20363', 'EV-20113', 'EV-20818', 'EV-20310',
       'EV-20521', 'EV-20608', 'EV-20788', 'EV-20849', 'EV-20106',
       'EV-20621', 'EV-20637', 'EV-20174', 'EV-20022', 'EV-20072',
       'EV-20312', 'EV-20999', 'EV-20971', 'EV-20092', 'EV-20089',
       'EV-20178', 'EV-20678', 'EV-20907', 'EV-20665', 'EV-20543',
       'EV-20714', 'EV-20724', 'EV-20958', 'EV-20218', 'EV-20779',
       'EV-20504', 'EV-20555', 'EV-20112', 'EV-20088', 'EV-20638',
       'EV-20628', 'EV-20487', 'EV-20912', 'EV-20996', 'EV-20944',
       'EV-20454', 'EV-20368', 'EV-20266', 'EV-20086', 'EV-20231',
       'EV-20036', 'EV-20649', 'EV-20744', 'EV-20422', 'EV-20005',
       'EV-20457', 'EV-20737', 'EV-20446', 'EV-20830', 'EV-20816',
       'EV-20429', 'EV-20219', 'EV-20467', 'EV-20447', 'EV-20880',
       'EV-20281', 'EV-20149', 'EV-20444', 'EV-20558', 'EV-20898',
       'EV-20716', 'EV-20148', 'EV-20514', 'EV-20449', 'EV-20313',
       'EV-20680', 'EV-20793', 'EV-20615', 'EV-20976', 'EV-20400',
       'EV-20094', 'EV-20224', 'EV-20634', 'EV-20261', 'EV-20736',
       'EV-20322', 'EV-20509', 'EV-20474', 'EV-20428', 'EV-20586',
       'EV-20466', 'EV-20666', 'EV-20988', 'EV-20087', 'EV-20144',
       'EV-20906', 'EV-20345', 'EV-20477', 'EV-20812', 'EV-20761',
       'EV-20125', 'EV-20277', 'EV-20143', 'EV-20279', 'EV-20863',
       'EV-20181', 'EV-20017', 'EV-20232', 'EV-20702', 'EV-20047',
       'EV-20157', 'EV-20740', 'EV-20978', 'EV-20475', 'EV-20406',
       'EV-20334', 'EV-20823', 'EV-20754', 'EV-20027', 'EV-20414',
       'EV-20164', 'EV-20760', 'EV-20442', 'EV-20212', 'EV-20683',
       'EV-20820', 'EV-20641', 'EV-20881', 'EV-20204', 'EV-20197',
       'EV-20139', 'EV-20722', 'EV-20791', 'EV-20661', 'EV-20573',
       'EV-20209', 'EV-20375', 'EV-20826', 'EV-20378', 'EV-20223',
       'EV-20844', 'EV-20592', 'EV-20298', 'EV-20009', 'EV-20327',
       'EV-20840', 'EV-20207', 'EV-20915', 'EV-20080', 'EV-20975',
       'EV-20096', 'EV-20137', 'EV-20192', 'EV-20962', 'EV-20052',
       'EV-20020', 'EV-20458', 'EV-20443', 'EV-20743', 'EV-20064',
       'EV-20361', 'EV-20896', 'EV-20341', 'EV-20290', 'EV-20348',
       'EV-20350', 'EV-20319', 'EV-20222', 'EV-20411', 'EV-20131',
       'EV-20604', 'EV-20718', 'EV-20847', 'EV-20697', 'EV-20018',
       'EV-20346', 'EV-20574', 'EV-20731', 'EV-20567', 'EV-20698',
       'EV-20669', 'EV-20503', 'EV-20769', 'EV-20951', 'EV-20046',
       'EV-20989', 'EV-20981', 'EV-20031', 'EV-20836', 'EV-20265',
       'EV-20659', 'EV-20858', 'EV-20732', 'EV-20093', 'EV-20508',
       'EV-20546', 'EV-20773', 'EV-20759', 'EV-20498', 'EV-20496',
       'EV-20095', 'EV-20837', 'EV-20568', 'EV-20766', 'EV-20828',
       'EV-20329', 'EV-20531', 'EV-20000', 'EV-20195', 'EV-20076',
       'EV-20472', 'EV-20130', 'EV-20624', 'EV-20111', 'EV-20747',
       'EV-20717', 'EV-20305', 'EV-20550', 'EV-20992', 'EV-20482',
       'EV-20320', 'EV-20033', 'EV-20135', 'EV-20344', 'EV-20763',
       'EV-20010', 'EV-20395', 'EV-20768', 'EV-20711', 'EV-20037',
       'EV-20397', 'EV-20811', 'EV-20132', 'EV-20603', 'EV-20286',
       'EV-20167', 'EV-20723', 'EV-20575', 'EV-20016', 'EV-20899',
       'EV-20367', 'EV-20762', 'EV-20948', 'EV-20075', 'EV-20772',
       'EV-20750', 'EV-20512', 'EV-20417', 'EV-20513', 'EV-20522',
       'EV-20925', 'EV-20882', 'EV-20235', 'EV-20014', 'EV-20765',
       'EV-20481', 'EV-20670', 'EV-20012', 'EV-20434', 'EV-20937',
       'EV-20771', 'EV-20914', 'EV-20034', 'EV-20055', 'EV-20887',
       'EV-20485', 'EV-20394', 'EV-20415', 'EV-20062', 'EV-20438',
       'EV-20299', 'EV-20525', 'EV-20189', 'EV-20116', 'EV-20795',
       'EV-20129', 'EV-20213', 'EV-20595', 'EV-20328', 'EV-20357',
       'EV-20756', 'EV-20984', 'EV-20410', 'EV-20168'], dtype=object)

#### 2. Duplicate Vehicle Investigation
#### vehicle_id is expected to uniquely identify a vehicle.
#### Determine:
#### • how many duplicated vehicle_id values exist
#### • which vehicle IDs are duplicated
#### • how many records are affected
#### Then decide how you would handle these records without blindly using drop_duplicates().

In [46]:
import pandas as pd
df=pd.read_csv("C:\\Users\\HP\\Downloads\\EV_Resale_Price_Regression - EV_Resale_Price_Regression.csv")
df
duplicate= df['vehicle_id'].duplicated().sum()
print(duplicate)
duplicat_id=df.loc[df['vehicle_id'].duplicated(keep=False),'vehicle_id'].unique()
print(duplicat_id)
duplicate_records=(df[df['vehicle_id'].duplicated(keep=False)].sort_values('vehicle_id'))
print(duplicate_records)
affected_records=len(duplicate_records)
print(affected_records)

6
['EV-20515' 'EV-20653' 'EV-20011' 'EV-20544' 'EV-20193' 'EV-20279']
    vehicle_id listing_date  manufacture_year       brand vehicle_type  \
119   EV-20011   2025-04-30              2016      Nexora        Sedan
852   EV-20011   2027-05-03              2016      Nexora        Sedan
655   EV-20193   2026-10-18              2023     Atheron    Crossover
797   EV-20193   2027-03-09              2023     Atheron    Crossover
816   EV-20279   2027-03-28              2019    E-Motion          SUV
857   EV-20279   2027-05-08              2019    E-Motion          SUV
72    EV-20515   2025-03-14              2016  GreenDrive    Hatchback
621   EV-20515   2026-09-14              2016  GreenDrive    Hatchback
133   EV-20544   2025-05-14              2024    E-Motion        Sedan
280   EV-20544   2025-10-08              2024    E-Motion        Sedan
81    EV-20653   2025-03-23              2019     Atheron    Crossover
989   EV-20653   2027-09-17              2019     Atheron    Crossover

     battery_capacity_kwh  battery_health_pct  range_km  km_driven  \
119                  57.9                99.5       NaN    40831.0
852                  57.9                99.5       NaN    40831.0
655                  31.3                97.2     285.0    33740.0
797                  31.3                97.2     285.0    33740.0
816                  65.6                87.1     381.0   116102.0
857                  65.6                87.1     381.0   116102.0
72                   61.6               100.0     210.0    37482.0
621                  61.6               100.0     210.0    37482.0
133                  38.0                93.9     511.0    67782.0
280                  38.0                93.9     511.0    67782.0
81                   61.4                92.3     398.0    72412.0
989                  61.4                92.3     398.0    72412.0

     charging_time_hr fast_charging  owner_count       city service_history  \
119               8.4           Yes            4     Mumbai        Complete
852               8.4           Yes            4     Mumbai        Complete
655               8.1           Yes            4    Chennai        Complete
797               8.1           Yes            4    Chennai        Complete
816               6.8            No            2  Bengaluru        Complete
857               6.8            No            2  Bengaluru        Complete
72                7.0           Yes            1     Mumbai        Complete
621               7.0           Yes            1     Mumbai        Complete
133               3.1           Yes            2    Chennai        Complete
280               3.1           Yes            2    Chennai        Complete
81               10.6            No            4    Chennai        Complete
989              10.6            No            4    Chennai        Complete

     resale_price
119       1591429
852       1591429
655       1444991
797       1444991
816       1395622
857       1395622
72        1492498
621       1492498
133       1604620
280       1604620
81        1267473
989       1267473
12

#### 3. Date Conversion & Validation
#### Convert listing_date into a proper datetime column.
#### Then investigate:
#### • earliest listing date
#### • latest listing date
#### • invalid/missing dates
#### • whether the date column is suitable for feature engineering.

In [47]:
# Convert listing_date into datetime
df["listing_date"] = pd.to_datetime(df["listing_date"],errors="coerce")

# Check datatype
print(df["listing_date"].dtype)

# Earliest listing date
print("Earliest listing date:", df["listing_date"].min())

# Latest listing date
print("Latest listing date:", df["listing_date"].max())

# Count invalid/missing dates
print("Invalid/Missing dates:", df["listing_date"].isna().sum())

# Display rows having invalid/missing dates
print(df[df["listing_date"].isna()])

# Extract date features for feature engineering
df["listing_year"] = df["listing_date"].dt.year
df["listing_month"] = df["listing_date"].dt.month
df["listing_day"] = df["listing_date"].dt.day
df["listing_weekday"] = df["listing_date"].dt.day_name()

print(df.head())

datetime64[ns]
Earliest listing date: 2025-01-01 00:00:00
Latest listing date: 2027-09-27 00:00:00
Invalid/Missing dates: 0
Empty DataFrame
Columns: [vehicle_id, listing_date, manufacture_year, brand, vehicle_type, battery_capacity_kwh, battery_health_pct, range_km, km_driven, charging_time_hr, fast_charging, owner_count, city, service_history, resale_price]
Index: []
  vehicle_id listing_date  manufacture_year       brand vehicle_type  \
0   EV-20170   2025-01-01              2021      Nexora          SUV
1   EV-20530   2025-01-02              2025      Nexora    Crossover
2   EV-20654   2025-01-03              2019      Nexora    Crossover
3   EV-20935   2025-01-04              2022  GreenDrive    Hatchback
4   EV-20827   2025-01-05              2024  GreenDrive        Sedan

   battery_capacity_kwh  battery_health_pct  range_km    km_driven  \
0                  46.9                89.6     313.0   28454.0000
1                  80.6                99.5     543.0  183935.8448
2                  53.9                91.2       NaN   12003.0000
3                  60.1                89.3     528.0   13623.0000
4                  53.0                92.0     264.0   28548.0000

   charging_time_hr fast_charging  owner_count     city service_history  \
0              10.0            No            1  Chennai        Complete
1               7.1            No            2  Chennai        Complete
2               3.6           Yes            1  Chennai        Complete
3               7.8           Yes            2    Delhi        Complete
4               6.1            No            1     Pune        Complete

   resale_price  listing_year  listing_month  listing_day listing_weekday
0       1527836          2025              1            1       Wednesday
1       2040760          2025              1            2        Thursday
2       1830249          2025              1            3          Friday
3       1726422          2025              1            4        Saturday
4       1642232          2025              1            5          Sunday

#### 4. Vehicle Age Feature
#### Create vehicle_age using:
#### listing year − manufacture year
#### Then identify whether any vehicle has:
#### • age < 0
#### • age = 0

#### 5. Battery Data Imputation
#### The following columns contain missing values:
#### battery_capacity_kwh, battery_health_pct, range_km, charging_time_hr
#### Develop an appropriate missing-value strategy for each column.
#### Do not automatically use the same statistic for every column.

#### 6. Battery Health Outlier Investigation
#### Analyze battery_health_pct.
#### Identify:
#### • values below a reasonable minimum
#### • values above 100
#### • extreme observations
#### Then decide whether to remove, cap, or retain suspicious values.

#### 7. Range vs Battery Capacity
#### Create range_per_kwh using:
#### range_km / battery_capacity_kwh
#### Identify vehicles with unusually low or high efficiency.

#### 8. Driving Intensity Feature
#### Create km_per_year using:
#### km_driven / vehicle_age
#### Handle the special case where vehicle_age = 0.
#### Identify unusually high annual driving.

#### 9. Charging Efficiency
#### Create charging_efficiency using:
#### range_km / charging_time_hr
#### Investigate missing values and extreme values before using this feature in a regression model.

#### 10. Ownership Analysis
#### Analyze owner_count.
#### Determine:
#### • frequency of each ownership level
#### • whether any values are invalid
#### • whether owner count should be treated as numerical or categorical for regression.
#### Justify your decision.

#### 11. Categorical Data Audit
#### Analyze: brand, vehicle_type, fast_charging, city, service_history.
#### For each column:
#### • count unique categories
#### • inspect frequencies
#### • identify missing values
#### • identify suspicious/inconsistent categories.

#### 12. Service History Cleaning
#### service_history contains Complete, Partial, Missing, and NaN.
#### Determine whether “Missing” and actual NaN represent the same business meaning.
#### Then create a consistent representation suitable for ML.

#### 13. Fast Charging Transformation
#### Transform fast_charging from Yes / No into a binary numerical representation.
#### Verify the transformation using frequency counts before and after.

#### 14. Target Analysis
#### Analyze resale_price.
#### Calculate and inspect:
#### • mean
#### • median
#### • minimum
#### • maximum
#### • standard deviation
#### • potential extreme values
#### Determine whether the target contains suspicious observations that could strongly influence a regression model.
####

#### 15. Price-per-Kilometer Feature
#### Create price_per_km using:
#### resale_price / km_driven
#### Investigate whether extremely low/high values are caused by very low mileage, very high price, or data-quality
#### problems.

#### 16. Battery Health × Usage Feature
#### Create a combined feature called battery_usage_index based on battery_health_pct and km_driven.
#### Design a meaningful formula and explain why this feature could help predict resale price.

#### 17. Complete Missing-Value Pipeline
#### Build a cleaning pipeline for all columns containing missing values:
#### battery_capacity_kwh, battery_health_pct, range_km, charging_time_hr, service_history
#### Requirements:
#### • numeric missing values → appropriate statistical treatment
#### • categorical missing values → appropriate category treatment
#### • verify zero unintended missing values afterward
#### • preserve the original dataset in a separate DataFrame.

#### 18. Regression Feature Preparation
#### Prepare the dataset for a regression model.
#### Separate:
#### X = features
#### y = resale_price
#### Remove columns that should not directly be used as model features, such as identifiers.
#### Classify every remaining feature as numerical, categorical, or date-derived.

#### 19. Leakage Investigation
#### Before training the regression model, inspect every engineered feature and determine whether it could cause
#### target leakage.
#### Evaluate whether features derived from resale_price should be allowed inside X.
#### Identify all problematic features and remove them.
####

#### 20. Ultimate Hard Problem — Production-Ready EV Dataset
#### You are given this raw EV resale dataset by a machine-learning team.
#### Build a clean modeling dataset following this workflow:
#### Step 1 — Audit: shape, info, missing values, duplicates, categorical distributions.
#### Step 2 — Clean identifiers: investigate duplicated vehicle_id values and determine an appropriate treatment.
#### Step 3 — Clean dates: convert listing_date and derive listing_year, listing_month, listing_quarter.
#### Step 4 — Clean numerical features: handle missing and suspicious values in battery_capacity_kwh,
#### battery_health_pct, range_km, km_driven, charging_time_hr, owner_count.
#### Step 5 — Clean categorical features: clean brand, vehicle_type, fast_charging, city, service_history.
#### Step 6 — Feature engineering: create vehicle_age, range_per_kwh, km_per_year, charging_efficiency,
#### battery_usage_index.
#### Step 7 — Leakage check: make sure no feature contains information derived from resale_price.
#### Step 8 — Final validation: no unintended duplicate vehicles, no invalid dates, no unexplained missing values,
#### correct numerical datatypes, consistent categorical values, no impossible vehicle ages, no impossible
#### battery-health values, and no target leakage.
#### Step 9 — Final output: produce X (cleaned independent variables) and y (resale_price).
#### Do not train a model. The task is to prepare a high-quality regression dataset